# Generated by Django 4.2.29 on 2026-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_manual_fix_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paused', models.BooleanField(default=False)),
                ('is_crashed', models.BooleanField(default=False)),
                ('is_skyrocketing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
