# Generated by Django 4.2.29 on 2026-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_marketcontrol_alter_alert_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
