# Generated by Django 4.2.29 on 2026-04-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_stock_icon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.DeleteModel(
            name='MarketControl',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='p2plisting',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='p2plisting',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='impact_percentage',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='event',
            name='impact_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='50000.00', max_digits=12),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='P2PListing',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
